export const jobs = [
  {
    employer: "Henan Putihrai Asset Management",
    jobTitle: "Software Engineer",
    postingTime: 2,
    location: "Indonesia",
    techStack: ["HTTP", "MVC", "Rest API", "Linus", "PostgreSQL", "Docker", "C++"],
    field: "Fullstack",
    rating: null,
    logo: "./8100.png",
    salary: "S$6,000 - S$8,000 / mth",
    est: false
  },
  {
    employer: "CharCentric",
    jobTitle: "Full-stack Software Engineer",
    postingTime: 3,
    location: "Indonesia",
    techStack: ["Strategy", "Next.js", "Docker", ".NET Core", "BigQuery", "UML", "Git"],
    field: "Fullstack",
    rating: null,
    logo: "./8933.png",
    salary: null,
    est: false
  },
  {
    employer: "Gojek",
    jobTitle: "Risk Data Engineer",
    postingTime: 6,
    location: "Indonesia",
    techStack: ["Analytics", "Storm", "Google Cloud", "Flow", "Java", "Airflow", "C++"],
    field: "Data Eng",
    rating: 4.3,
    logo: "./7.png",
    salary: "S$9,493 - S$18,997 / mth",
    est: true
  },
  {
    employer: "iZeno",
    jobTitle: "Data Engineer",
    postingTime: 10,
    location: "Thailand",
    techStack: ["Snowflake", "Jasper", "R", "Talend", "Dataiku", "UNIX", "Spotfire"],
    field: "Data Eng",
    rating: 3.3,
    logo: "./116.png",
    salary: null,
    est: false
  },
  {
    employer: "Osotspa",
    jobTitle: "Senior Full Stack Developer (ERP)",
    postingTime: 12,
    location: "Thailand",
    techStack: ["AWS", "Google Cloud", "Microsoft", "Apache", "Azure", "Java", "HTML"],
    field: "Fullstack",
    rating: null,
    logo: "./18436.png",
    salary: null,
    est: false
  },
  {
    employer: "PlayPark",
    jobTitle: "Sonior Developer Back-end C# .NET Core / Front-end",
    postingTime: 15,
    location: "Thailand",
    techStack: ["API", "JWT", ".NET Core", "OOP", "UML", "MSSQL", "JavaScript"],
    field: "Backend",
    rating: null,
    logo: "./3088.png",
    salary: null,
    est: false
  },
  {
    employer: "Fujitsu",
    jobTitle: "Application Engineer Manager (Retail Solution)",
    postingTime: 18,
    location: "Thailand",
    techStack: ["VB.Net", "MSSQL", "C#", ".NET"],
    field: "Fullstack",
    rating: 3.5,
    logo: "./1055.png",
    salary: null,
    est: false
  },
  {
    employer: "London Stock Exchange Group",
    jobTitle: "Development Team Lead (Angular, AWS)",
    postingTime: 19,
    location: "Thailand",
    techStack: ["AWS", "Svelte", "Sprint", "Azure", "Angular", "Typescript", "JavaScript"],
    field: "Fullstack",
    rating: 3.9,
    logo: "./1050.png",
    salary: null,
    est: false
  },
  {
    employer: "Amity",
    jobTitle: "Software Engineer (NodeJs)",
    postingTime: 23,
    location: "Thailand",
    techStack: ["AWS", "Rest API", "API", "Node.js"],
    field: "Fullstack",
    rating: 5,
    logo: "./3147.png",
    salary: null,
    est: false
  },
  {
    employer: "EPAM Systems",
    jobTitle: "Senior .NET Engineer",
    postingTime: 25,
    location: "Thailand",
    techStack: ["AWS", "Rest API", "Go", "CI", "SNS", ".NET Core", "SQS"],
    field: "Fullstack",
    rating: 4.4,
    logo: "./1196.png",
    salary: null,
    est: false
  },
]
